import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Layout from "../../lib/Layout";
// import SocialPostContainer from "../components/SocialPost/SocialPostContainer";
const inter = Inter({ subsets: ["latin"] });

export default function Manager() {
  return (
    <Layout>
      <Head>
        <title>Weave - Zenroll</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* <PostCard /> */}
        {/* <SocialPostContainer /> */}
      </main>
    </Layout>
  );
}
