import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Layout from "../../../lib/Layout";
// import SocialPostContainer from "../components/SocialPost/SocialPostContainer";
const inter = Inter({ subsets: ["latin"] });
import {
  Box,
  chakra,
  Flex,
  SimpleGrid,
  Stat,
  StatLabel,
  StatNumber,
  useColorModeValue,
} from "@chakra-ui/react";
import StatsCard from "../../../components/StatsCard";
import PostNewJob from "../../../components/Forms/PostNewJob";
export default function PostJob() {
  return (
    <Layout>
      <Head>
        <title>Weave - Zenroll</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Flex
          maxW="7xl"
          // h={"100vh"}
          mt={32}
          mx={"auto"}
          // pt={1}
          justify={"center"}
          align={"center"}
          // my={"auto"}
          px={{ base: 2, sm: 12, md: 17 }}
        >
          <PostNewJob />
        </Flex>
      </main>
    </Layout>
  );
}
